[package]
name = "crossbeam_test"
version = "0.1.0"
authors = ["Visic"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
name = "plugin"
path = "src/plugin.rs"

[[bin]]
name = "crossbeam_test"
path = "src/main.rs"

[dependencies]
libloading = "0.5.2"
crossbeam-channel = "0.3.9"